# Generated by Django 5.2.13 on 2026-05-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_available',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=10),
        ),
    ]
