# Generated by Django 5.2.13 on 2026-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_size_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_available',
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.CharField(default='M', help_text='Example: S,M,L,XL', max_length=100),
        ),
    ]
