# Generated by Django 5.2.13 on 2026-05-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={},
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='updated_at',
        ),
    ]
